config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :seat_numbers
  resources :bus_services do 
    collection do
      get 'sync_calendar'
      get 'service_status'
    end
  end

  resources :bookings do 
    collection do
      post 'bus_booking'
      match ':action(/:id(.:format))', via: [:get, :post]
    end
  end
  # resources :home
  resources :home do
    collection do
      # get "google_auth"
      # post "google_auth2"
      match ':action(/:id(.:format))', via: [:get, :post]
    end
  end
  resources :room_numbers
  resources :room_types
  resources :hotels do
    collection do
      get 'index'
      get 'google_calendar'
      post 'create_google_calendar'
    end
  end
  resources :buses do
    collection do
      get 'index'
      get 'google_calendar'
      get 'buses_calendar_mapping'
      post 'save_bus_calendar_mapping'
      post 'create_google_calendar'
      get 'search_bus'
      get 'search_service_result'
    end
  end

  root to: "buses#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bus_service.rb
class BusService < ApplicationRecord
	def BusService.get_bus_services_array(user_id)
		@bus_services = BusService.where("user_id=?", user_id)
    @bus_services_array = []
    @bus_services.each {|bus_service|
      @bus_services_array << [bus_service.name, bus_service.id]
    }
    return @bus_services_array
	end
end

app/controllers/bus_services_controller.rb
class BusServicesController < ApplicationController
  before_action :set_bus_service, only: [:show, :edit, :update, :destroy]

  # GET /bus_services
  # GET /bus_services.json
  def index
    @bus_services = BusService.where("user_id=?", current_user.id)
    @cities = City.get_cities_hash
  end

  # GET /bus_services/1
  # GET /bus_services/1.json
  def show
  end

  # GET /bus_services/new
  def new
    @bus_service = BusService.new
    @cities = City.get_cities_array
  end

  # GET /bus_services/1/edit
  def edit
    @cities = City.get_cities_array
  end

  def sync_calendar
    user = current_user
    @gcal_code = user.gcal_code
    gcal = GCal.new(@gcal_code)
    begin
      event_lists = gcal.list_events(params["cal_id"], user.id)
      render plain: 1
    rescue => ex
      render plain: 2
    end
  end

  # POST /bus_services
  # POST /bus_services.json
  def create
    @bus_service = BusService.new(bus_service_params)

    respond_to do |format|
      if @bus_service.save
        format.html { redirect_to @bus_service, notice: 'Bus service was successfully created.' }
        format.json { render :show, status: :created, location: @bus_service }
      else
        format.html { render :new }
        format.json { render json: @bus_service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bus_services/1
  # PATCH/PUT /bus_services/1.json
  def update
    respond_to do |format|
      if @bus_service.update(bus_service_params)
        format.html { redirect_to @bus_service, notice: 'Bus service was successfully updated.' }
        format.json { render :show, status: :ok, location: @bus_service }
      else
        format.html { render :edit }
        format.json { render json: @bus_service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bus_services/1
  # DELETE /bus_services/1.json
  def destroy
    @bus_service.destroy
    respond_to do |format|
      format.html { redirect_to bus_services_url, notice: 'Bus service was successfully destroyed.' }
      format.json {k head :no_content }
    end
  end

  def service_status
    @bus_service = BusService.find params[:service_id]
    @user = User.find params[:user_id]
    status = params[:status].to_i == 1 ? 2 : 1
    @mapping = BusCalendarMapping.where("bus_service_id=?", params[:service_id]).first
    if !@user.gcal_code.blank? and !@mapping.blank?
      @gcal_code = @user.gcal_code
      gcal = GCal.new(@gcal_code)
      if status == 2
        mobile_no = AdminType::SMS_ALERT_NUMBERS
        mobile_no.each do |phone_number|
          guest_message = "Hi sir/madam Your Bus Ticket Booked Successfully "
          SmsOut.send_sms(@user.id,phone_number ,guest_message)
        end
        message = "Hi sir/madam Your Bus service ticket Booked successfully"
        SmsOut.send_sms(@user.id,@user.mobile_number ,message)
        result = gcal.create_new_event(@bus_service.journey_date, @mapping.google_calendar_id)
        @bus_service.update_attributes(status: status, event_id: result.id)
      else
        mobile_no = AdminType::SMS_ALERT_NUMBERS
        mobile_no.each do |phone_number|
          guest_message = "Hi sir/madam Your Bus Ticket Blocked Successfully "
          SmsOut.send_sms(@user.id,phone_number ,guest_message)
        end
        message = "Hi sir/madam Your Bus service ticket Blocked successfully"
        SmsOut.send_sms(@user.id,@user.mobile_number ,message)
        result = gcal.delete_event(@bus_service.event_id, @mapping.google_calendar_id)
        @bus_service.update_attributes(status: status, event_id: nil)
      end
    end
    render partial: "service_status"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bus_service
      @bus_service = BusService.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bus_service_params
      params.require(:bus_service).permit(:name, :status, :user_id, :origin, :destination, :journey_date)
    end
end

app/helpers/bus_services_helper.rb
module BusServicesHelper
end

app/views/bus_services/_form.html.erb
<%= form_with(model: bus_service, local: true, :html=>{:class=>"new_service"}) do |form| %>
  <% if bus_service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bus_service.errors.count, "error") %> prohibited this bus_service from being saved:</h2>

      <ul>
      <% bus_service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, :class => "new_booking" %>
  </div>

  <div class="field">
    <%= form.label :origin %>
    <%= form.select :origin , @cities ,{}, :class => "new_booking" %>
  </div>

  <div class="field">
    <%= form.label :destination %>
    <%= form.select :destination , @cities ,{}, :class => "new_booking" %>
  </div>

  <div class="field">
    <%= form.label :journey_date %>

  <span id="datepicker1" class="input-group date" data-date-format="dd/mm/yyyy">
    <%= form.text_field :journey_date , :class => "new_booking form-control" %>
    <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i>
     </span>
  </div>
 

  <div class="field">
    <%= form.hidden_field :user_id, value: "#{current_user.id}" %>
    
  </div>

  <!-- <div class="field"> -->
    <%#= form.label :status %>
    <%#= form.number_field :status %>
  <!-- </div> -->

  <div class="actions">
    <%= form.submit :class => "btn btn-primary" %>
  </div>
<% end %>

 <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.js"></script>

<script type="text/javascript">
$(function () {
  $("#datepicker1").datepicker({ 
        autoclose: true, 
        todayHighlight: true
  }).datepicker('update', new Date());
});

 </script>

app/views/bus_services/_service_status.html.erb
<% if @bus_service.status.to_i == 1 %>
  <a href='javascript:void(0)' onclick='changeServiceStatus("<%=@bus_service.status%>","<%=@bus_service.id%>","<%=@user.id%>")'>Active</a>
<% else %>
  <a href='javascript:void(0)' onclick='changeServiceStatus("<%=@bus_service.status%>","<%=@bus_service.id%>","<%=@user.id%>")'>Cancelled</a>
<% end %>

<script type="text/javascript">
	alert("Status Changed Successfully")
</script>

app/views/bus_services/_success.html.erb
<div id="mail_success" class='message'>
				  <div class='check'>&#10004;</div>
				  <p>Success </p>
				  <p>Thank you for your successful registration, We will check and getback to you!</p>
				  <button id='agent-success'>OK</button>
				</div>

app/views/bus_services/edit.html.erb
<h1>Editing Bus Service</h1>

<%= render 'form', bus_service: @bus_service %>

<%= link_to 'Show', @bus_service ,:class => "btn btn-primary" %> 
<%= link_to 'Back', bus_services_path ,:class => "btn"%>

app/views/bus_services/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bus Services</h1>

<table class="bus_service">
  <thead>
    <tr>
      <th>Name</th>
      <th>Origin</th>
      <th>Destination</th>
      <th>Journey Date</th>
      <th>Status</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bus_services.each do |bus_service| %>
      <tr>
        <td><%= bus_service.name %></td>
        <td><%= @cities[bus_service.origin] %></td>
        <td><%= @cities[bus_service.destination] %></td>
        <td><%= bus_service.journey_date %></td>
        <td><div id="service_status_<%=bus_service.id%>"><% if bus_service.status.to_i == 1 %>
              <a href='javascript:void(0)' onclick='changeServiceStatus("<%=bus_service.status%>","<%=bus_service.id%>","<%=current_user.id%>")'>Active</a>
              <% else %>
               <a href='javascript:void(0)' onclick='changeServiceStatus("<%=bus_service.status%>","<%=bus_service.id%>","<%=current_user.id%>")'>Cancelled</a>
              <% end %></div></td>

        <td><%= link_to 'Edit', edit_bus_service_path(bus_service) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
 
<%= link_to 'New Bus Service', new_bus_service_path ,:class => "btn btn-primary" %>

<script type="text/javascript">
  function changeServiceStatus(status, serviceId, userId){
    $("#service_status_"+serviceId).load("/bus_services/service_status?&status="+status+"&service_id="+serviceId+"&user_id="+userId)
  }
</script>

app/views/bus_services/new.html.erb
<h1>New Bus Service</h1>

<%= render 'form', bus_service: @bus_service %>

<%= link_to 'Back', bus_services_path ,:class => "btn" %>

app/views/bus_services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bus_service.name %>
</p>



<%= link_to 'Edit', edit_bus_service_path(@bus_service) ,:class => "btn btn-primary" %> 
<%= link_to 'Back', bus_services_path ,:class => "btn" %>