config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :seat_numbers
  resources :bus_services do 
    collection do
      get 'sync_calendar'
      get 'service_status'
    end
  end

  resources :bookings do 
    collection do
      post 'bus_booking'
      match ':action(/:id(.:format))', via: [:get, :post]
    end
  end
  # resources :home
  resources :home do
    collection do
      # get "google_auth"
      # post "google_auth2"
      match ':action(/:id(.:format))', via: [:get, :post]
    end
  end
  resources :room_numbers
  resources :room_types
  resources :hotels do
    collection do
      get 'index'
      get 'google_calendar'
      post 'create_google_calendar'
    end
  end
  resources :buses do
    collection do
      get 'index'
      get 'google_calendar'
      get 'buses_calendar_mapping'
      post 'save_bus_calendar_mapping'
      post 'create_google_calendar'
      get 'search_bus'
      get 'search_service_result'
    end
  end

  root to: "buses#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/seat_number.rb
class SeatNumber < ApplicationRecord
end

app/controllers/seat_numbers_controller.rb
class SeatNumbersController < ApplicationController
  before_action :set_seat_number, only: [:show, :edit, :update, :destroy]

  # GET /seat_numbers
  # GET /seat_numbers.json
  def index
    @seat_numbers = SeatNumber.where("user_id=?", current_user.id)
    @bus_services = BusService.all
    @bus_services_hash = {}
    @bus_services.each {|bus_service|
      @bus_services_hash[bus_service.id] = bus_service.name
    }
  end

  # GET /seat_numbers/1
  # GET /seat_numbers/1.json
  def show
  end

  # GET /seat_numbers/new
  def new
    @seat_number = SeatNumber.new
    @bus_services = BusService.where("user_id=?", current_user.id)
    @bus_services_array = []
    @bus_services.each {|bus_service|
      @bus_services_array << [bus_service.name, bus_service.id]
    }
  end

  # GET /seat_numbers/1/edit
  def edit
    @bus_services = BusService.where("user_id=?", current_user.id)
    @bus_services_array = []
    @bus_services.each {|bus_service|
      @bus_services_array << [bus_service.name, bus_service.id]
    }
  end

  # POST /seat_numbers
  # POST /seat_numbers.json
  def create
    @seat_number = SeatNumber.new(seat_number_params)

    respond_to do |format|
      if @seat_number.save
        format.html { redirect_to @seat_number, notice: 'Seat number was successfully created.' }
        format.json { render :show, status: :created, location: @seat_number }
      else
        format.html { render :new }
        format.json { render json: @seat_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seat_numbers/1
  # PATCH/PUT /seat_numbers/1.json
  def update
    respond_to do |format|
      if @seat_number.update(seat_number_params)
        format.html { redirect_to @seat_number, notice: 'Seat number was successfully updated.' }
        format.json { render :show, status: :ok, location: @seat_number }
      else
        format.html { render :edit }
        format.json { render json: @seat_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seat_numbers/1
  # DELETE /seat_numbers/1.json
  def destroy
    @seat_number.destroy
    respond_to do |format|
      format.html { redirect_to seat_numbers_url, notice: 'Seat number was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seat_number
      @seat_number = SeatNumber.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seat_number_params
      params.require(:seat_number).permit(:seat_number, :bus_service_id, :status, :user_id)
    end
end

app/helpers/seat_numbers_helper.rb
module SeatNumbersHelper
end

app/views/seat_numbers/_form.html.erb
<%= form_with(model: seat_number, local: true,:class=>"seat_number") do |form| %>
  <% if seat_number.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(seat_number.errors.count, "error") %> prohibited this seat_number from being saved:</h2>

      <ul>
      <% seat_number.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :bus_service_id %>
    <%= form.select :bus_service_id , @bus_services_array ,{}, :class => "" %>
  </div>
  
  <div class="field">
    <%= form.label :seat_number %>
    <%= form.text_field :seat_number %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, value: "#{current_user.id}" %>
  </div>

  <!-- <div class="field"> -->
    <%#= form.label :status %>
    <%#= form.number_field :status %>
  <!-- </div> -->

  <div class="actions">
    <%= form.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/seat_numbers/edit.html.erb
<h1>Editing Seat Number</h1>

<%= render 'form', seat_number: @seat_number %>

<%= link_to 'Show', @seat_number ,:class => "btn btn-primary" %> 
<%= link_to 'Back', seat_numbers_path ,:class => "btn" %>

app/views/seat_numbers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Seat Numbers</h1>

<table class="seat_number">
  <thead>
    <tr>
      <th>Seat number</th>
      <th>Bus service</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @seat_numbers.each do |seat_number| %>
      <tr>
        <td><%= seat_number.seat_number %></td>
        <td><%= @bus_services_hash[seat_number.bus_service_id] %></td>
        <td><%= link_to 'Edit', edit_seat_number_path(seat_number) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Seat Number', new_seat_number_path ,:class => "btn btn-primary" %>

app/views/seat_numbers/new.html.erb
<h1>New Seat Number</h1>

<%= render 'form', seat_number: @seat_number %>

<%= link_to 'Back', seat_numbers_path ,:class => "btn"%>

app/views/seat_numbers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Seat number:</strong>
  <%= @seat_number.seat_number %>
</p>

<p>
  <strong>Bus service:</strong>
  <%= @seat_number.bus_service_id %>
</p>


<%= link_to 'Edit', edit_seat_number_path(@seat_number) ,:class => "btn btn-primary"%> 
<%= link_to 'Back', seat_numbers_path ,:class => "btn"%>