config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :seat_numbers
  resources :bus_services do 
    collection do
      get 'sync_calendar'
      get 'service_status'
    end
  end

  resources :bookings do 
    collection do
      post 'bus_booking'
      match ':action(/:id(.:format))', via: [:get, :post]
    end
  end
  # resources :home
  resources :home do
    collection do
      # get "google_auth"
      # post "google_auth2"
      match ':action(/:id(.:format))', via: [:get, :post]
    end
  end
  resources :room_numbers
  resources :room_types
  resources :hotels do
    collection do
      get 'index'
      get 'google_calendar'
      post 'create_google_calendar'
    end
  end
  resources :buses do
    collection do
      get 'index'
      get 'google_calendar'
      get 'buses_calendar_mapping'
      post 'save_bus_calendar_mapping'
      post 'create_google_calendar'
      get 'search_bus'
      get 'search_service_result'
    end
  end

  root to: "buses#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GCalendar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Lato|Roboto:300,400,500,700" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   
  </head>

  <body>


    <% if user_signed_in? %>
<div class="wrapper">
        <nav id="sidebar">
            <div class="sidebar-header">
              <a class="navbar-brand" href="/">
              <img src="/assets/g_calnder_2-.png" class="logo logo-display" alt="">
            </a>
               
            </div>

            

            <ul class="list-unstyled components">
               
                
                <li>
                   <%= link_to "Services", "#{bus_services_path}" %>
                </li>
                <li>
                    <%= link_to "Seat Numbers", "#{seat_numbers_path}" %>
                </li>
                <% if current_user.gcal_code.blank? %>
                  <li>
                    <%= link_to "Google Cal Mapping",  {:action => "google_auth", :controller => "/home"}, :html =>{:is_as_link => true}, :title => "Google Cal Mapping" %>
                  </li>
                <% end %>
                 <li>
                    <%= link_to "Google Calendars", "#{google_calendar_buses_path}" %>
                </li>
                 <li>
                    <%= link_to "Bus Calendar Mapping", "#{buses_calendar_mapping_buses_path}" %>
                </li>
                 <li>
                    <%= link_to "Search", "#{search_bus_buses_path}" %>
                </li> 
            </ul>

            
        </nav>

        <div id="content">
            <nav class="navbar navbar-default navbar-fixed navbar-transparent white bootsnav">
        <div class="container-fluid">         
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-menu">
            <i class="fa fa-bars" aria-hidden="true"></i>
          </button>
          

          <div class="collapse navbar-collapse" id="navbar-menu">
            
            <ul class="nav navbar-nav navbar-right" data-in="fadeInDown" data-out="fadeOutUp">
             <% if user_signed_in? %>
      <li>
      <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
      </li>
   
    <% end %>
            </ul>
          </div>
        </div>   
      </nav>
      <div class="common-block">
      <%= yield %>
    </div>

        </div>

    </div>


    <% else %>

      <%= yield %>
    <% end %>

    
    
    
  </body>
</html>